### ISSUE TITLE
B: IP based location integration

### ISSUE THREAD

**Issue by Megastrik3** [Megastrik3/Megastrik3.github.io#42]

**Comment by andrewgomoll2** [comment]
this issue is code complete and waiting to be merged into the project. This code is in branch "current_location_code". The current functionality is that the user hits the "Use my current location" button, then we first get their lat long, then convert the lat long to a city. Future implementation will include calling the API's to fetch weather and activity data and passing in the city field

**Comment by Megastrik3** [comment]
Looks good! Great work!
